-- Phase 6 P6-2, migration 2 of 5: catalog semantics of the Phase 6 permissions (design section 9, P6-T24).
-- No data is changed and nothing is granted. The constraint is rewritten with the previous lists (last set by
-- 20261030000001_phase5_referral) plus the new codes.
--
-- GLOBAL_ONLY (never grantable at a branch scope; the overrides trigger already refuses a GLOBAL_ONLY code below GLOBAL by
-- reading `permissions.scope_capability`): MANAGE_PRODUCTS, MANAGE_PRODUCT_PRICES, VIEW_PRODUCT_COST, IMPORT_PRODUCT_DATA,
-- MANAGE_PRODUCT_CAMPAIGNS. Branch capable: VIEW_INVENTORY, MANAGE_STOCK_RECEIPTS, ADJUST_STOCK, SELL_PRODUCTS,
-- MANAGE_PRODUCT_RETURNS, REFUND_PRODUCTS.
-- FINANCIAL data: MANAGE_PRODUCT_PRICES, VIEW_PRODUCT_COST, MANAGE_STOCK_RECEIPTS, IMPORT_PRODUCT_DATA, REFUND_PRODUCTS,
-- MANAGE_PRODUCT_CAMPAIGNS. Everything else new is STANDARD. None of them is Owner-only: the Owner grants them.
ALTER TABLE "permissions" DROP CONSTRAINT "permissions_catalog_semantics";
ALTER TABLE "permissions"
  ADD CONSTRAINT "permissions_catalog_semantics" CHECK (
    (("code" IN ('MANAGE_SERVICE_PRICES', 'MANAGE_BOOKING_SETTINGS', 'MANAGE_DISCOUNTS', 'CREATE_VOUCHERS',
          'MANAGE_WEBSITE_CONTENT', 'ADJUST_LOYALTY_POINTS', 'MANAGE_COMBOS', 'RESTORE_COMBO_SESSIONS',
          'MANAGE_BIRTHDAY_REWARDS', 'MANAGE_REWARD_CATALOG', 'VIEW_LOYALTY_EXCEPTIONS', 'ACTIVATE_LOYALTY',
          'CHANGE_REFERRER', 'MANAGE_PRODUCTS', 'MANAGE_PRODUCT_PRICES', 'VIEW_PRODUCT_COST', 'IMPORT_PRODUCT_DATA',
          'MANAGE_PRODUCT_CAMPAIGNS')
        AND "scope_capability" = 'GLOBAL_ONLY')
      OR ("code" NOT IN ('MANAGE_SERVICE_PRICES', 'MANAGE_BOOKING_SETTINGS', 'MANAGE_DISCOUNTS', 'CREATE_VOUCHERS',
          'MANAGE_WEBSITE_CONTENT', 'ADJUST_LOYALTY_POINTS', 'MANAGE_COMBOS', 'RESTORE_COMBO_SESSIONS',
          'MANAGE_BIRTHDAY_REWARDS', 'MANAGE_REWARD_CATALOG', 'VIEW_LOYALTY_EXCEPTIONS', 'ACTIVATE_LOYALTY',
          'CHANGE_REFERRER', 'MANAGE_PRODUCTS', 'MANAGE_PRODUCT_PRICES', 'VIEW_PRODUCT_COST', 'IMPORT_PRODUCT_DATA',
          'MANAGE_PRODUCT_CAMPAIGNS')
        AND "scope_capability" = 'BRANCH_CAPABLE'))
    AND (("code" IN ('VIEW_EMPLOYEE_PAY', 'MANAGE_EMPLOYEE_PAY') AND "data_classification" = 'EMPLOYEE_PAY')
      OR ("code" IN ('VIEW_INVOICES', 'MANAGE_INVOICES', 'COLLECT_PAYMENTS', 'APPLY_DISCOUNTS',
          'MANAGE_DISCOUNTS', 'CREATE_VOUCHERS', 'CANCEL_INVOICES', 'CORRECT_PAYMENTS', 'VIEW_REVENUE',
          'ADJUST_LOYALTY_POINTS', 'RESTORE_COMBO_SESSIONS', 'MANAGE_PRODUCT_PRICES', 'VIEW_PRODUCT_COST',
          'MANAGE_STOCK_RECEIPTS', 'IMPORT_PRODUCT_DATA', 'REFUND_PRODUCTS', 'MANAGE_PRODUCT_CAMPAIGNS')
        AND "data_classification" = 'FINANCIAL')
      OR ("code" NOT IN ('VIEW_EMPLOYEE_PAY', 'MANAGE_EMPLOYEE_PAY', 'VIEW_INVOICES', 'MANAGE_INVOICES',
          'COLLECT_PAYMENTS', 'APPLY_DISCOUNTS', 'MANAGE_DISCOUNTS', 'CREATE_VOUCHERS', 'CANCEL_INVOICES',
          'CORRECT_PAYMENTS', 'VIEW_REVENUE', 'ADJUST_LOYALTY_POINTS', 'RESTORE_COMBO_SESSIONS',
          'MANAGE_PRODUCT_PRICES', 'VIEW_PRODUCT_COST', 'MANAGE_STOCK_RECEIPTS', 'IMPORT_PRODUCT_DATA',
          'REFUND_PRODUCTS', 'MANAGE_PRODUCT_CAMPAIGNS')
        AND "data_classification" = 'STANDARD'))
  );
